const seedPosts = [
  { id: 'attention', type: 'Essay', category: 'Essays', title: 'The quiet architecture of attention', excerpt: 'A field guide to making room for the thoughts that do not arrive with a notification sound.', body: 'Attention is not a personality trait. It is a place we make. It lives in the spaces between the alert and the answer, in the walk without a podcast, in the notebook left open on the table.\n\nThe work is not to become unreachable. It is to decide what deserves to reach us.', author: 'Mina Kwon', date: 'Sep 12, 2026', read: '8 min read', color: 'rust', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=85' },
  { id: 'small-internet', type: 'Essay', category: 'Culture', title: 'Notes from the small internet', excerpt: 'What gets better when the audience gets smaller, the edges get softer, and nobody is optimizing for reach.', body: 'The best rooms on the internet still feel like rooms. They have a scale you can hold in your head, a few familiar names, and enough context to make a strange idea feel welcome.', author: 'Theo Hart', date: 'Sep 08, 2026', read: '6 min read', color: 'blue', image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=85' },
  { id: 'useful-things', type: 'Essay', category: 'Making', title: 'Make useful things slowly', excerpt: 'A reminder that craft is not a speed bump on the way to scale. Sometimes it is the whole road.', body: 'There is a particular satisfaction in making something that does one job well. It asks you to stay close to the material, notice the awkward edge, and let the work teach you what it needs.', author: 'Mina Kwon', date: 'Aug 29, 2026', read: '5 min read', color: 'green', image: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=900&q=85' },
]
const postTypes = ['Essay', 'Poem', 'Novel', 'Letter', 'Birthday special']
const config = window.FIELDNOTES_CONFIG || {}
const supabaseConfigured = Boolean(config.supabaseUrl && config.supabaseAnonKey && !config.supabaseAnonKey.includes('PASTE_') && window.supabase?.createClient)
const supabase = supabaseConfigured ? window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey) : null
let posts = readPosts()
let user = null
let saved = JSON.parse(localStorage.getItem('fieldnotes-saved') || '[]')
let activeFilter = 'All notes'
let selectedPost = null
let messages = [{ from: 'bot', text: 'Hello. I’m the Fieldnotes guide. Ask me about a format, publishing, sharing, or finding something to read.' }]

function readPosts() { try { return JSON.parse(localStorage.getItem('fieldnotes-posts')) || seedPosts } catch { return seedPosts } }
function esc(value = '') { return String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])) }
function postView(post) { return { ...post, type: post.type || post.post_type || 'Essay', image: post.image || seedPosts[1].image, read: post.read || `${post.read_time || 1} min read` } }
function notice(text) { document.getElementById('noticeRoot').innerHTML = `<div class="data-notice">${esc(text)}<button aria-label="Dismiss">×</button></div>`; document.querySelector('.data-notice button').onclick = () => document.getElementById('noticeRoot').innerHTML = '' }
function persist() { localStorage.setItem('fieldnotes-posts', JSON.stringify(posts)); localStorage.setItem('fieldnotes-saved', JSON.stringify(saved)) }
function toggleSaved(id) { saved = saved.includes(id) ? saved.filter((item) => item !== id) : [...saved, id]; persist(); render() }
function filtered() { const query = document.getElementById('searchInput').value.toLowerCase(); return posts.filter((post) => (activeFilter === 'All notes' || post.category === activeFilter || post.type === activeFilter) && `${post.title} ${post.excerpt} ${post.author}`.toLowerCase().includes(query)) }
function render() {
  const featured = postView(posts[0]);
  if (!featured) return
  document.getElementById('featuredPost').innerHTML = `<div class="featured-image ${featured.color}" style="background-image:url('${featured.image}')"><span class="image-label">${esc(featured.type)} / Fieldnotes</span></div><div class="featured-content"><p class="post-meta">${esc(featured.type)} <span /> ${esc(featured.category)} <span /> ${esc(featured.read)}</p><h2>${esc(featured.title)}</h2><p>${esc(featured.excerpt)}</p><div class="post-footer"><span>By ${esc(featured.author)} · ${esc(featured.date)}</span><button class="save-button ${saved.includes(featured.id) ? 'saved' : ''}" data-save="${featured.id}">${saved.includes(featured.id) ? 'Saved' : 'Save note'} <span>↗</span></button></div></div>`
  document.getElementById('featuredPost').onclick = (event) => event.target.closest('[data-save]') ? toggleSaved(featured.id) : openReader(featured)
  const categories = ['All notes', ...new Set(posts.map((post) => post.category))]
  document.getElementById('filters').innerHTML = [...categories, ...postTypes].map((filter) => `<button class="category ${activeFilter === filter ? 'active' : ''}" data-filter="${esc(filter)}">${esc(filter)}</button>`).join('')
  document.querySelectorAll('[data-filter]').forEach((button) => { button.onclick = () => { activeFilter = button.dataset.filter; render() } })
  const items = filtered().slice(activeFilter === 'All notes' && !document.getElementById('searchInput').value ? 1 : 0)
  document.getElementById('postGrid').innerHTML = items.map((post) => { const item = postView(post); return `<article class="post-card" data-post="${esc(item.id)}"><div class="post-image ${item.color}" style="background-image:url('${item.image}')"><span class="post-category">${esc(item.type)}</span></div><div class="post-card-content"><div class="post-card-top"><span>${esc(item.read)}</span><button class="bookmark ${saved.includes(item.id) ? 'saved' : ''}" data-save="${esc(item.id)}">${saved.includes(item.id) ? '●' : '○'}</button></div><h3>${esc(item.title)}</h3><p>${esc(item.excerpt)}</p><span class="card-byline">${esc(item.author)} · ${esc(item.date)}</span></div></article>` }).join('')
  document.getElementById('emptyState').hidden = items.length > 0
  document.querySelectorAll('[data-post]').forEach((card) => { card.onclick = (event) => event.target.closest('[data-save]') ? toggleSaved(card.dataset.post) : openReader(posts.find((post) => post.id === card.dataset.post)) })
}
function openReader(raw) { const post = postView(raw); selectedPost = post; document.getElementById('modalRoot').innerHTML = `<div class="reader-backdrop"><article class="reader-panel"><div class="reader-top"><span class="post-meta">${esc(post.type)} <span /> ${esc(post.category)} <span /> ${esc(post.read)}</span><button class="close-button" data-close>×</button></div><div class="reader-share-card" style="background-image:url('${post.image}')"><div><span>${esc(post.type)} / Fieldnotes</span><strong>${esc(post.title)}</strong><small>By ${esc(post.author)}</small></div></div><h2>${esc(post.title)}</h2><p class="reader-byline">By ${esc(post.author)} · ${esc(post.date)}</p><div class="reader-body">${esc(post.body || post.excerpt).split('\n\n').map((paragraph) => `<p>${paragraph}</p>`).join('')}</div><div class="reader-actions"><button class="share-button" data-share>Share image + link <span>↗</span></button><button class="save-button ${saved.includes(post.id) ? 'saved' : ''}" data-save>${saved.includes(post.id) ? 'Saved' : 'Save to your reading list'} <span>↗</span></button></div></article></div>`; document.querySelector('[data-close]').onclick = closeModal; document.querySelector('[data-share]').onclick = () => sharePost(post); document.querySelector('[data-save]').onclick = () => toggleSaved(post.id); document.querySelector('.reader-backdrop').onclick = (event) => { if (event.target === event.currentTarget) closeModal() } }
function closeModal() { selectedPost = null; document.getElementById('modalRoot').innerHTML = '' }
async function sharePost(post) { const url = `${location.origin}${location.pathname}#note-${post.id}`; try { if (navigator.share) await navigator.share({ title: post.title, text: `${post.title} by ${post.author} on Fieldnotes`, url }); else { await navigator.clipboard.writeText(url); notice('Link copied. Share it to WhatsApp, Instagram, Facebook, or your story.') } } catch (error) { if (error.name !== 'AbortError') notice('Copy the link from your browser and share it anywhere.') } }
function openAuth(mode = 'signin') { document.getElementById('modalRoot').innerHTML = `<div class="auth-backdrop"><form class="auth-panel"><div class="composer-heading"><div><p class="eyebrow">${mode === 'signup' ? 'Join Fieldnotes' : 'Welcome back'}</p><h2>${mode === 'signup' ? 'Make room<br><em>for your voice.</em>' : 'Continue<br><em>reading.</em>'}</h2></div><button type="button" class="close-button" data-close>×</button></div>${mode === 'signup' ? '<label>Name<input required name="name" placeholder="Your name"></label>' : ''}<label>Email<input required type="email" name="email" placeholder="you@example.com"></label><label>Password<input required minlength="6" type="password" name="password" placeholder="At least 6 characters"></label><p class="form-message" id="authMessage"></p><button class="publish-button auth-submit">${mode === 'signup' ? 'Create account' : 'Sign in'} <span>↗</span></button><button type="button" class="google-button" id="googleButton"><span class="google-mark">G</span>Continue with Google</button><button type="button" class="switch-auth" id="switchAuth">${mode === 'signup' ? 'Already have an account? Sign in' : 'New here? Create an account'}</button></form></div>`; document.querySelector('[data-close]').onclick = closeModal; document.querySelector('#googleButton').onclick = () => supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: location.origin } }); document.querySelector('#switchAuth').onclick = () => openAuth(mode === 'signup' ? 'signin' : 'signup'); document.querySelector('.auth-panel').onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = mode === 'signup' ? await supabase.auth.signUp({ email: form.get('email'), password: form.get('password'), options: { data: { display_name: form.get('name') } } }) : await supabase.auth.signInWithPassword({ email: form.get('email'), password: form.get('password') }); if (result.error) document.getElementById('authMessage').textContent = result.error.message; else if (mode === 'signup') document.getElementById('authMessage').textContent = 'Check your email to confirm your account, then sign in.'; else { user = result.data.user; document.getElementById('accountButton').textContent = 'Writer studio'; closeModal(); openDashboard() } } }
async function openDashboard() { if (!user) return openAuth(); document.querySelector('main').hidden = true; document.getElementById('writerDashboard').hidden = false; const ownPosts = posts.filter((post) => post.author_id === user.id || post.author === (user.user_metadata?.display_name || user.email)); document.getElementById('writerDashboard').innerHTML = `<div class="dashboard-shell"><div class="dashboard-top"><div><p class="eyebrow">Writer studio</p><h1>Your fieldnotes.</h1><p>${esc(user.user_metadata?.display_name || user.email)}</p></div><div class="dashboard-actions"><button class="dashboard-home" id="dashboardHome">Home</button><button class="publish-button" id="dashboardWrite">Write a note <span>+</span></button><button class="account-trigger" id="dashboardLogout">Log out</button></div></div><div class="dashboard-stats"><div><strong>${ownPosts.length}</strong><span>Published notes</span></div><div><strong>${saved.length}</strong><span>Saved for later</span></div><div><strong>Fieldnotes</strong><span>Your writing home</span></div></div><div class="dashboard-heading"><p class="eyebrow">Your library</p><h2>Notes you have made.</h2></div><div class="dashboard-grid">${ownPosts.length ? ownPosts.map((post) => `<article class="dashboard-note"><span>${esc(post.type || post.post_type || 'Essay')}</span><h3>${esc(post.title)}</h3><p>${esc(post.excerpt)}</p><small>${esc(post.date || 'Published')}</small></article>`).join('') : '<p class="empty-state">Your published notes will appear here.</p>'}</div></div>`; document.getElementById('dashboardHome').onclick = showHome; document.getElementById('dashboardWrite').onclick = openComposer; document.getElementById('dashboardLogout').onclick = logout }
function showHome() { document.querySelector('main').hidden = false; document.getElementById('writerDashboard').hidden = true; window.scrollTo({ top: 0, behavior: 'smooth' }) }
async function logout() { if (supabase) await supabase.auth.signOut(); user = null; document.getElementById('accountButton').textContent = 'Sign in'; showHome(); notice('You are signed out.') }
function openComposer() { if (!supabaseConfigured) return notice('Add your Supabase publishable key in src/config.js first.'); if (!user) return openAuth(); document.getElementById('modalRoot').innerHTML = `<div class="composer-backdrop"><form class="composer-panel"><div class="composer-heading"><div><p class="eyebrow">New contribution</p><h2>Put something<br><em>into the world.</em></h2></div><button type="button" class="close-button" data-close>×</button></div><label>Title<input required name="title" placeholder="Give your note a name"></label><div class="composer-row"><label>By<input required name="author" placeholder="Your name"></label><label>Format<select name="type">${postTypes.map((type) => `<option>${type}</option>`).join('')}</select></label></div><label>Section<select name="category"><option>Essays</option><option>Culture</option><option>Making</option><option>Community</option></select></label><label>Your piece<textarea required minlength="40" name="body" placeholder="What have you been thinking about?"></textarea></label><div class="composer-footer"><span>Your note will appear in the public library.</span><button class="publish-button">Publish note <span>↗</span></button></div></form></div>`; document.querySelector('[data-close]').onclick = closeModal; document.querySelector('.composer-panel').onsubmit = publish }
async function publish(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = form.get('body').trim(); const payload = { title: form.get('title').trim(), excerpt: body.slice(0, 142), body, post_type: form.get('type'), category: form.get('category'), author: form.get('author').trim(), author_id: user.id, read_time: Math.max(1, Math.ceil(body.split(/\s+/).length / 180)) }; const { data, error } = await supabase.from('posts').insert(payload).select().single(); if (error) return notice(error.message); posts.unshift(data); closeModal(); render(); const { error: notifyError } = await supabase.functions.invoke('notify-new-post', { body: { post: data, siteUrl: location.origin } }); if (notifyError) notice('Published, but subscriber email delivery is not configured yet.') }
async function subscribe(event) { event.preventDefault(); const email = new FormData(event.currentTarget).get('email'); const { error } = supabaseConfigured ? await supabase.from('subscribers').insert({ email }) : { error: null }; if (error && error.code !== '23505') return notice(error.message); document.getElementById('subscribeMessage').textContent = 'Welcome to the quiet corner of your inbox.'; event.currentTarget.reset() }
function answer(text) { const value = text.toLowerCase(); if (value.includes('poem')) return 'Choose Poem in Write a note. Poems, fragments, and spoken-word drafts are welcome.'; if (value.includes('publish') || value.includes('submit')) return 'Create an account, choose Write a note, select a format, and publish it to the library.'; if (value.includes('share')) return 'Open a note and tap Share. On mobile it opens the share sheet; on desktop it copies the link.'; if (value.includes('birthday')) return 'Birthday specials are perfect for dedications, memories, tributes, and celebrations.'; if (value.includes('novel')) return 'Publish novels as serialized chapters by choosing the Novel format.'; if (value.includes('letter')) return 'Letters to friends, strangers, history, or your future self are welcome.'; return 'Ask me about poems, novels, letters, birthday specials, publishing, sharing, or saving notes.' }
function openChat() { document.getElementById('modalRoot').innerHTML = `<div class="chat-panel" role="dialog" aria-label="Fieldnotes guide"><div class="chat-header"><div><span class="status-dot"></span>Fieldnotes guide</div><button type="button" data-close aria-label="Close guide">×</button></div><div class="chat-messages" id="messages">${messages.map((message) => `<div class="message ${message.from}">${esc(message.text)}</div>`).join('')}</div><div class="suggestions">${['Recommend a poem', 'How do I publish?', 'How do I share a note?'].map((item) => `<button type="button" data-suggestion="${esc(item)}">${esc(item)}</button>`).join('')}</div><form class="chat-form"><input autocomplete="off" placeholder="Ask a question..." aria-label="Ask the guide"><button type="submit" aria-label="Send question">↑</button></form></div>`; document.querySelector('[data-close]').onclick = closeModal; document.querySelectorAll('[data-suggestion]').forEach((button) => button.onclick = () => sendChat(button.dataset.suggestion)); document.querySelector('.chat-form').onsubmit = (event) => { event.preventDefault(); const input = event.currentTarget.querySelector('input'); const text = input.value.trim(); if (text) { input.value = ''; sendChat(text) } } }
function sendChat(text) { if (!text) return; messages.push({ from: 'user', text }, { from: 'bot', text: answer(text) }); openChat() }
async function uploadCover(file) { if (!file) return null; const path = `${user.id}/${Date.now()}-${file.name.replace(/[^a-z0-9.]+/gi, '-')}`; const { error } = await supabase.storage.from('covers').upload(path, file, { upsert: false, contentType: file.type }); if (error) throw error; return supabase.storage.from('covers').getPublicUrl(path).data.publicUrl }
async function publishWithCover(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = form.get('body').trim(); const cover = form.get('cover'); if (!cover || !cover.size) return notice('Choose a cover image before publishing.'); if (cover.size > 5 * 1024 * 1024) return notice('Cover images must be 5 MB or smaller.'); const button = event.currentTarget.querySelector('.publish-button'); button.disabled = true; button.textContent = 'Publishing...'; try { const image = await uploadCover(cover); const payload = { title: form.get('title').trim(), excerpt: body.slice(0, 142), body, post_type: form.get('type'), category: form.get('category'), author: form.get('author').trim(), author_id: user.id, read_time: Math.max(1, Math.ceil(body.split(/\s+/).length / 180)), image }; const { data, error } = await supabase.from('posts').insert(payload).select().single(); if (error) throw error; posts.unshift(data); closeModal(); render(); if (!document.getElementById('writerDashboard').hidden) openDashboard(); const { error: notifyError } = await supabase.functions.invoke('notify-new-post', { body: { post: data, siteUrl: location.origin } }); if (notifyError) notice('Published, but subscriber email delivery is not configured yet.') } catch (error) { button.disabled = false; button.textContent = 'Publish note ↗'; notice(error.message || 'Could not publish this note. Check the covers bucket policy.') } }
function enhanceComposer(form) { if (form.querySelector('[name="cover"]')) return; const label = document.createElement('label'); label.innerHTML = 'Cover image<input required accept="image/jpeg,image/png,image/webp" type="file" name="cover"><small class="cover-help">JPG, PNG, or WebP up to 5 MB.</small><img class="cover-preview" alt="Cover preview">'; const bodyLabel = form.querySelector('[name="body"]').closest('label'); bodyLabel.before(label); const input = label.querySelector('input'); const preview = label.querySelector('img'); input.onchange = () => { const file = input.files[0]; if (file && file.size <= 5 * 1024 * 1024) preview.src = URL.createObjectURL(file); else if (file) { input.value = ''; notice('Cover images must be 5 MB or smaller.') } }; form.onsubmit = publishWithCover }
const composerObserver = new MutationObserver(() => { const form = document.querySelector('.composer-panel'); if (form) enhanceComposer(form) }); composerObserver.observe(document.getElementById('modalRoot'), { childList: true, subtree: true })

document.getElementById('searchInput').oninput = render
document.getElementById('accountButton').onclick = () => { if (!supabaseConfigured) return notice('Supabase is not configured yet.'); if (user) openDashboard(); else openAuth('signin') }
document.getElementById('writeButton').onclick = openComposer
document.getElementById('shareYours').onclick = openComposer
document.getElementById('chatButton').onclick = openChat
document.getElementById('subscribeForm').onsubmit = subscribe
if (supabaseConfigured) { supabase.auth.getSession().then(({ data }) => { user = data.session?.user || null; document.getElementById('accountButton').textContent = user ? 'Writer studio' : 'Sign in' }); supabase.auth.onAuthStateChange((_event, session) => { user = session?.user || null; document.getElementById('accountButton').textContent = user ? 'Writer studio' : 'Sign in' }); supabase.from('posts').select('*').order('created_at', { ascending: false }).then(({ data }) => { if (data?.length) { posts = data; render() } }) }
render()
